# Generated by Django 3.2.6 on 2021-08-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.TextField()),
                ('res_relation', models.ForeignKey(default='No relations', on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.TextField()),
                ('mile_relation', models.ForeignKey(default='No relations', on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
            ],
        ),
    ]
