# Generated by Django 3.2.6 on 2021-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_milestone_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='mile_des',
            field=models.TextField(default='No description'),
        ),
    ]
